### ISSUE TITLE
Not possible to connect to remote server

### ISSUE THREAD

**Issue by mamac** [grodansparadis/vscp#226]
With version:12.29.2.8 Magnesium

Trying to connect to an older vscpd server, I got the message below.
![image](https://user-images.githubusercontent.com/7148802/32517369-88d8e26c-c406-11e7-9d80-b613f1c68765.png)

Thank you

**Comment by grodansparadis** [comment]
Same version of VSCP Works and server?

**Comment by mamac** [comment]
Server is VSCP Daemon version: 1.0.1.7 Neon
WORKS is version 12.29.2.8 Magnesium

**Comment by grodansparadis** [comment]
I don't say it is but that can be the problem. The reason is the addition of the datetime earlier which broke all old interfaces. So a late version of VSCP Works to an old server and vice versa will have problem.  But VSCP Works worktrough for the upcoming release is still  not done so it can be some other problem also.  Hopefully I will be there in a week or two.

**Comment by grodansparadis** [comment]
I can confirm that this was a problem also on later versions, all due to a missing compile switch.  This is fixed in 12.29.2.12 Magnesium.

**Comment by mamac** [comment]
Indeed, it works now :-)
Thank you very much Ake!

**Comment by grodansparadis** [comment]
Thanks for the heads up!
